/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.AdoptionModel;

/**
 *
 * @author Acer
 */
public class AdoptionPannel extends javax.swing.JPanel {

    /**
     * Creates new form AdoptionPannel
     */
    public AdoptionPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ImpAdoptionno = new javax.swing.JLabel();
        ImpAdoptionImg = new javax.swing.JLabel();
        ImpAdoptionname = new javax.swing.JLabel();
        ImpAdoptionspecies = new javax.swing.JLabel();
        ImpAdoptionAge = new javax.swing.JLabel();
        ImpAdoptionbirthday = new javax.swing.JLabel();
        ImpAdoptioninfo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(906, 221));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBackground(new java.awt.Color(233, 150, 89));

        ImpAdoptionno.setText("Contact no-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImpAdoptionno)
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImpAdoptionno)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        ImpAdoptionImg.setText("img");

        ImpAdoptionname.setText("Name : ");

        ImpAdoptionspecies.setText("Species :");

        ImpAdoptionAge.setText("Age :");

        ImpAdoptionbirthday.setText("Bitrhday:");

        ImpAdoptioninfo.setText("About-    ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImpAdoptionImg)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImpAdoptionbirthday)
                    .addComponent(ImpAdoptionAge)
                    .addComponent(ImpAdoptionspecies)
                    .addComponent(ImpAdoptionname))
                .addGap(88, 88, 88)
                .addComponent(ImpAdoptioninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImpAdoptionImg)
                            .addComponent(ImpAdoptionname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ImpAdoptionspecies)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ImpAdoptionAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ImpAdoptionbirthday))
                    .addComponent(ImpAdoptioninfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImpAdoptionAge;
    private javax.swing.JLabel ImpAdoptionImg;
    private javax.swing.JLabel ImpAdoptionbirthday;
    private javax.swing.JLabel ImpAdoptioninfo;
    private javax.swing.JLabel ImpAdoptionname;
    private javax.swing.JLabel ImpAdoptionno;
    private javax.swing.JLabel ImpAdoptionspecies;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getImpAdoptionnameField() {
return ImpAdoptionname;
}
    public javax.swing.JLabel getImpAdoptionnoField() {
return ImpAdoptionno;
}
    public javax.swing.JLabel getImpAdoptionAgeField() {
return ImpAdoptionAge;
}
    public javax.swing.JLabel getImpAdoptionspeciesField() {
return ImpAdoptionspecies;
}

public javax.swing.JLabel getImpAdoptioninfoField() {
return ImpAdoptioninfo;
}
    public javax.swing.JLabel getImpAdoptionImgField() {
return ImpAdoptionImg;
}
public void setAdoptionPannel(AdoptionModel product) {
    ImpAdoptionname.setText("Name: " + product.getAdoptname());
    ImpAdoptionAge.setText("Name: " + product.getAdoptage ());
    ImpAdoptionno.setText("Name: " + product.getAdoptno());
    ImpAdoptionname.setText("Name: " + product.getAdoptname());
    
    ImageIcon icon = new ImageIcon(product.getAdoptionImg());
    Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    ImpAdoptionImg.setIcon(new ImageIcon(img));
}
}
