
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.ProductModel;

public class ProductCard2 extends javax.swing.JPanel {


    public ProductCard2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImpProductname2 = new javax.swing.JLabel();
        ImpProductprice2 = new javax.swing.JLabel();
        ImpProductrating2 = new javax.swing.JLabel();
        Productimg2 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ImpProductname2.setText("name");

        ImpProductprice2.setText("price");

        ImpProductrating2.setText("rating");

        Productimg2.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Productimg2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ImpProductname2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImpProductprice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImpProductrating2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Productimg2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImpProductname2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImpProductprice2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImpProductrating2)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImpProductname2;
    private javax.swing.JLabel ImpProductprice2;
    private javax.swing.JLabel ImpProductrating2;
    private javax.swing.JLabel Productimg2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public javax.swing.JLabel getImpProductname2Field() {
return ImpProductname2;
}
public javax.swing.JLabel getImpProductprice2Field() {
return ImpProductprice2;
}
public javax.swing.JLabel getImpProductrating2Field() {
return ImpProductrating2;
}
public javax.swing.JLabel getProductimg2Field() {
return Productimg2;
}
public void setProduct(ProductModel product) {
    ImpProductname2.setText("Name: " + product.getProductName());
    ImpProductprice2.setText("Price: Rs " + product.getProductPrice());
    ImpProductrating2.setText("Rating:  " + product.getProductRating());

    ImageIcon icon = new ImageIcon(product.getImg());
    Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    Productimg2.setIcon(new ImageIcon(img));
}
}
